const variedades = [
  { nombre: "Cremon bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Maisy Lime Green", color: "Bicolor", nochesLuz: 20 },
  { nombre: "Sunflame yellow Cremon", color: "Yellow", nochesLuz: 20 },
  { nombre: "Tutu", color: "White", nochesLuz: 17 },
  { nombre: "Bronky Cremon", color: "Bronce", nochesLuz: 17 },
  { nombre: "Cremon Artic Queen", color: "White", nochesLuz: 17 },
  { nombre: "Cremon Astroid Yellow", color: "Yellow", nochesLuz: 10 },
  { nombre: "Cremon Bernal Yellow", color: "Yellow", nochesLuz: 17 },
  { nombre: "Cremon Bronze Roatan", color: "Bronce", nochesLuz: 17 },
  { nombre: "Cremon Gaviria Purple", color: "Purple", nochesLuz: 20 },
  { nombre: "Cremon Kirvy Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Cremon Kirvy Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Cremon Lamira Purple", color: "Purple", nochesLuz: 17 },
  { nombre: "Cremon Lamira Red", color: "Red", nochesLuz: 17 },
  { nombre: "Cremon Nexus Purple", color: "Purple", nochesLuz: 17 },
  { nombre: "Cremon Pretuzca Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Cremon Veronica", color: "Pink", nochesLuz: 10 },
  { nombre: "Cremon White Chita", color: "White", nochesLuz: 17 },
  { nombre: "Pao Spider", color: "Yellow", nochesLuz: 17 },
  { nombre: "Romancero", color: "Salmon", nochesLuz: 20 },
  { nombre: "Spider Bronze Chewbacca", color: "Bronce", nochesLuz: 20 },
  { nombre: "Spider Clemente Green", color: "Green", nochesLuz: 14 },
  { nombre: "Spider Linette Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Spider Pink ray", color: "Pink", nochesLuz: 17 },
  { nombre: "Spider Ray", color: "Pink", nochesLuz: 17 },
  { nombre: "Spider Tiana Purple", color: "Purple", nochesLuz: 22 },
  { nombre: "Spider Yazoo White", color: "White", nochesLuz: 17 },
  { nombre: "Topspink White Spider", color: "White", nochesLuz: 17 },
  { nombre: "Towi Cremon", color: "White", nochesLuz: 17 },
  { nombre: "Bronze Asst", color: "Bronce", nochesLuz: 17 },
  { nombre: "Cushion Kirvy Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Cushion Kirvy Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Cushion Skylie", color: "White", nochesLuz: 17 },
  { nombre: "Disco Club", color: "Bicolor", nochesLuz: 17 },
  { nombre: "Micro Crazy Cluz", color: "White", nochesLuz: 17 },
  { nombre: "Micro Powi", color: "Yellow", nochesLuz: 17 },
  { nombre: "Pompo Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Pompon Purple", color: "Purple", nochesLuz: 17 },
  { nombre: "Pompon White", color: "White", nochesLuz: 17 },
  { nombre: "Pompon Yellow", color: "Yellow", nochesLuz: 17 },
  { nombre: "Red Asst", color: "Red", nochesLuz: 17 },
  { nombre: "Yellow Stone", color: "Yellow", nochesLuz: 17 },
  { nombre: "Zippo", color: "Yellow", nochesLuz: 17 },
  { nombre: "Artiga", color: "Purple", nochesLuz: 14 },
  { nombre: "Becky Pink", color: "Pink", nochesLuz: 22 },
  { nombre: "Bronze Melito", color: "Bronce", nochesLuz: 17 },
  { nombre: "Country Green", color: "Green", nochesLuz: 16 },
  { nombre: "Eagle White", color: "White", nochesLuz: 20 },
  { nombre: "Lexy Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Lexy Red", color: "Red", nochesLuz: 17 },
  { nombre: "Melito Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Paintball Sunny Yellow", color: "Yellow", nochesLuz: 22 },
  { nombre: "Peptalk", color: "Green", nochesLuz: 20 },
  { nombre: "Peptalk Green", color: "Green", nochesLuz: 20 },
  { nombre: "Rosenda Red", color: "Red", nochesLuz: 17 },
  { nombre: "Silva", color: "Green", nochesLuz: 14 },
  { nombre: "Sweet Purple", color: "Purple", nochesLuz: 17 },
  { nombre: "Uva Purple", color: "Uva Purple", nochesLuz: 17 },
  { nombre: "Whatssap Green", color: "Green", nochesLuz: 20 },
  { nombre: "Lamira Red", color: "Red", nochesLuz: 17 },
  { nombre: "Artic Queen White", color: "White", nochesLuz: 17 },
  { nombre: "Astroid Yellow", color: "Yellow", nochesLuz: 10 },
  { nombre: "Bernal Yellow", color: "Yellow", nochesLuz: 17 },
  { nombre: "Bonita", color: "White", nochesLuz: 17 },
  { nombre: "Bronky", color: "Bronce", nochesLuz: 17 },
  { nombre: "Bronze Bombay", color: "Bronce", nochesLuz: 17 },
  { nombre: "Candor Light Bicolor", color: "Bicolor", nochesLuz: 17 },
  { nombre: "Candor Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Candy Vintage", color: "Vintage", nochesLuz: 17 },
  { nombre: "Cooper Bronze", color: "Bronce", nochesLuz: 14 },
  { nombre: "Cored Red", color: "Red", nochesLuz: 17 },
  { nombre: "Cushion Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Cushion Bronze Fogata", color: "Bronce", nochesLuz: 17 },
  { nombre: "Cushion Bronze Woodstar", color: "Bronce", nochesLuz: 17 },
  { nombre: "Cushion Red", color: "Red", nochesLuz: 17 },
  { nombre: "Dina", color: "Pink", nochesLuz: 14 },
  { nombre: "Dorito", color: "Bronce", nochesLuz: 14 },
  { nombre: "Drum Bronze", color: "Bronce", nochesLuz: 22 },
  { nombre: "Empata Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Fogata Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Guadalajara", color: "White", nochesLuz: 17 },
  { nombre: "Isabel Red", color: "Red", nochesLuz: 17 },
  { nombre: "Journey Purple", color: "Purple", nochesLuz: 10 },
  { nombre: "Lambrusco", color: "Pink", nochesLuz: 17 },
  { nombre: "Logan White", color: "White", nochesLuz: 17 },
  { nombre: "Lovesno", color: "White", nochesLuz: 17 },
  { nombre: "Lynx Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Maisy Lime Green", color: "Green", nochesLuz: 20 },
  { nombre: "Maisy White", color: "White", nochesLuz: 20 },
  { nombre: "Mimosa Yellow", color: "Yellow", nochesLuz: 17 },
  { nombre: "Orange Drum", color: "Orange", nochesLuz: 22 },
  { nombre: "Orange Veronica", color: "Orange", nochesLuz: 10 },
  { nombre: "Pasion Almendra Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Paul Purple", color: "Purple", nochesLuz: 17 },
  { nombre: "Paulina Purple", color: "Purple", nochesLuz: 10 },
  { nombre: "Petruzca Pink", color: "Petruzca Pink", nochesLuz: 17 },
  { nombre: "Rigoletto", color: "Yellow", nochesLuz: 14 },
  { nombre: "Rioja Red", color: "Red", nochesLuz: 17 },
  { nombre: "Romancero Bicolor", color: "Bicolor", nochesLuz: 20 },
  { nombre: "Salmon Linnete", color: "Salmon", nochesLuz: 17 },
  { nombre: "Soleado Yellow", color: "Yellow", nochesLuz: 17 },
  { nombre: "Sulma", color: "Yellow", nochesLuz: 24 },
  { nombre: "Sunflame Yellow", color: "Yellow", nochesLuz: 20 },
  { nombre: "Thyrza Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Tinted Burgundy", color: "Burgundy", nochesLuz: 17 },
  { nombre: "Tondo Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Tornado Purple", color: "Purple", nochesLuz: 17 },
  { nombre: "Trissia Bicolor", color: "Bicolor", nochesLuz: 10 },
  { nombre: "Veronica Pink", color: "Pink", nochesLuz: 10 },
  { nombre: "Woodstar Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Xrist Green", color: "Green", nochesLuz: 22 },
  { nombre: "Yellow Bernal", color: "Yellow", nochesLuz: 17 },
  { nombre: "Zembla Sunny Yellow", color: "Yellow", nochesLuz: 24 },
  { nombre: "Abby", color: "Red", nochesLuz: 17 },
  { nombre: "Alma White", color: "White", nochesLuz: 22 },
  { nombre: "Amor Nival White", color: "White", nochesLuz: 20 },
  { nombre: "Anita", color: "White", nochesLuz: 17 },
  { nombre: "Atlantis Bronze", color: "Bronce", nochesLuz: 14 },
  { nombre: "Atlantis Pink", color: "Pink", nochesLuz: 14 },
  { nombre: "Atlantis Red", color: "Red", nochesLuz: 14 },
  { nombre: "Atlantis White", color: "White", nochesLuz: 14 },
  { nombre: "Atlantis Yellow", color: "Yellow", nochesLuz: 14 },
  { nombre: "Balsas Purple", color: "Purple", nochesLuz: 17 },
  { nombre: "Bicolor Handsome", color: "Bicolor", nochesLuz: 10 },
  { nombre: "Bicolor Yellow Red Flick", color: "Bicolor", nochesLuz: 17 },
  { nombre: "Brahma Red", color: "Red", nochesLuz: 10 },
  { nombre: "Broncestone Bronce", color: "Bronce", nochesLuz: 17 },
  { nombre: "Bronze Ragusa", color: "Bronce", nochesLuz: 17 },
  { nombre: "Candela Bronze", color: "Bronce", nochesLuz: 10 },
  { nombre: "Chilly paper Red", color: "Red", nochesLuz: 17 },
  { nombre: "Clon 5 Red", color: "Red", nochesLuz: 17 },
  { nombre: "Daisy Lina", color: "Orange", nochesLuz: 17 },
  { nombre: "Daisy Red", color: "Red", nochesLuz: 17 },
  { nombre: "Daisy Yellow Top Dollar", color: "Yellow", nochesLuz: 17 },
  { nombre: "Flick Bicolor", color: "Bicolor", nochesLuz: 20 },
  { nombre: "Frescolita White", color: "White", nochesLuz: 20 },
  { nombre: "Handsome Bicolor", color: "Bicolor", nochesLuz: 10 },
  { nombre: "Harley Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Harley Red", color: "Red", nochesLuz: 17 },
  { nombre: "Indira Yellow", color: "Yellow", nochesLuz: 14 },
  { nombre: "Kastellin Bicolor", color: "Bicolor", nochesLuz: 17 },
  { nombre: "Kintaro Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Kintaro Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Managua Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Morning Bicolor", color: "Bicolor", nochesLuz: 17 },
  { nombre: "Natalia Bronze", color: "Bronce", nochesLuz: 14 },
  { nombre: "Nela", color: "Pink", nochesLuz: 10 },
  { nombre: "Nerello Red", color: "Red", nochesLuz: 20 },
  { nombre: "Orange Managua", color: "Orange", nochesLuz: 17 },
  { nombre: "Orinoco Bicolor", color: "Bicolor", nochesLuz: 20 },
  { nombre: "Orinoco Purple", color: "Purple", nochesLuz: 20 },
  { nombre: "Palma Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Peach Kintaro", color: "Peach", nochesLuz: 17 },
  { nombre: "Pink Alma", color: "Pink", nochesLuz: 22 },
  { nombre: "Pom Daisy White", color: "White", nochesLuz: 17 },
  { nombre: "Redbull Red", color: "Red", nochesLuz: 17 },
  { nombre: "Resplandor Bicolor", color: "Bicolor", nochesLuz: 14 },
  { nombre: "Rihana Pink", color: "Pink", nochesLuz: 14 },
  { nombre: "Salmon Tequila", color: "Salmon", nochesLuz: 17 },
  { nombre: "Show Purple", color: "Purple", nochesLuz: 14 },
  { nombre: "Starfire", color: "Bicolor", nochesLuz: 14 },
  { nombre: "Tequila", color: "Salmon", nochesLuz: 17 },
  { nombre: "Tokio White", color: "White", nochesLuz: 10 },
  { nombre: "Top Dollar", color: "White", nochesLuz: 17 },
  { nombre: "Valentino Red", color: "Red", nochesLuz: 17 },
  { nombre: "Vitamin C", color: "Red", nochesLuz: 14 },
  { nombre: "Adele Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Alejandra", color: "Yellow", nochesLuz: 17 },
  { nombre: "Amaze Pink", color: "Pink", nochesLuz: 22 },
  { nombre: "Amaze Purple", color: "Purple", nochesLuz: 22 },
  { nombre: "Azufre", color: "Yellow", nochesLuz: 17 },
  { nombre: "Baltica", color: "White", nochesLuz: 17 },
  { nombre: "Bicolor Sundy", color: "Bicolor", nochesLuz: 17 },
  { nombre: "Caramelo Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Cheddar Yellow", color: "Yellow", nochesLuz: 17 },
  { nombre: "Coqueta Green", color: "Green", nochesLuz: 14 },
  { nombre: "Empatia Sunset Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "Esponja", color: "White", nochesLuz: 17 },
  { nombre: "Green Wasowsky", color: "Green", nochesLuz: 17 },
  { nombre: "Ivanovo Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Ivanovo White", color: "White", nochesLuz: 17 },
  { nombre: "Jamaica Green/Yellow", color: "Green/Yellow", nochesLuz: 17 },
  { nombre: "Kans", color: "Pink", nochesLuz: 17 },
  { nombre: "Kans Pink Dark", color: "Pink", nochesLuz: 17 },
  { nombre: "Lenox Yellow", color: "Yellow", nochesLuz: 10 },
  { nombre: "Mapi", color: "Pink", nochesLuz: 17 },
  { nombre: "Motow Red", color: "Red", nochesLuz: 14 },
  { nombre: "Needle White", color: "White", nochesLuz: 17 },
  { nombre: "Novelty Pink", color: "Pink", nochesLuz: 17 },
  { nombre: "Novelty Red Urban", color: "Red", nochesLuz: 17 },
  { nombre: "Peach Adele", color: "Peach", nochesLuz: 17 },
  { nombre: "Shock Purple", color: "Purple", nochesLuz: 22 },
  { nombre: "Troyes Purple", color: "Purple", nochesLuz: 17 },
  { nombre: "Turo Bronze", color: "Bronce", nochesLuz: 14 },
  { nombre: "Unica White", color: "White", nochesLuz: 20 },
  { nombre: "Will", color: "Purple", nochesLuz: 17 },
  { nombre: "Yellow Poewi", color: "Yellow", nochesLuz: 17 },
  { nombre: "Yellow Viking", color: "Yellow", nochesLuz: 17 },
  { nombre: "Zippo Yellow", color: "Yellow", nochesLuz: 17 },
  { nombre: "Ruscus Green", color: "Green", nochesLuz: 17 },
  { nombre: "Solidago", color: "Yellow", nochesLuz: 17 },
  { nombre: "Anastasia Bronce", color: "Bronce", nochesLuz: 20 },
  { nombre: "Anastasia Special White", color: "White", nochesLuz: 20 },
  { nombre: "Bronce Tierra Spider", color: "Bronce", nochesLuz: 17 },
  { nombre: "Bronze Chispa Spider", color: "Bronce", nochesLuz: 14 },
  { nombre: "Calafuria", color: "Orange", nochesLuz: 17 },
  { nombre: "Calafuria Disbud", color: "Yellow", nochesLuz: 17 },
  { nombre: "Hidra Pink", color: "Pink", nochesLuz: 14 },
  { nombre: "Lilac", color: "Lila", nochesLuz: 17 },
  { nombre: "Quartz Green", color: "Green", nochesLuz: 3 },
  { nombre: "Spider Bronze", color: "Bronce", nochesLuz: 17 },
  { nombre: "White Yazoo", color: "White", nochesLuz: 17 },
  { nombre: "Vincent Choice", color: "Sunflower", nochesLuz: 0 }
];

module.exports = variedades;